name: ESLint

on: [push, pull_request]

jobs:
  eslint:
    name: Run eslint scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: main

    - name: Checkout ESLint config repository
      uses: actions/checkout@v4
      with:
        path: lint
        repository: SaiCode-DEV/WMELint

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - uses: actions/cache@v3
      id: npm-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/eslint.config.mjs') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install ESLint config dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: |
        cd lint
        npm install

    - run: ls lint
    - run: ls main

    - name: Run ESLint
      run: |
        cd lint
        npx eslint "../main/**/*.js" --config ./eslint.config.mjs
