name: ESLint

on: [push, pull_request]

jobs:
  eslint:
    name: Run eslint scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Checkout ESLint config repository
      uses: actions/checkout@v4
      with:
        repository: SaiCode-DEV/WMELint

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - uses: actions/cache@v3
      id: npm-cache
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install ESLint config dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm install

    - name: Run ESLint
      run: npx eslint "**/*.js" --config eslint.config.mjs
